spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_ssm?serverTimezone=UTC
    username: root
    password: jing
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      aop-patterns: com.lee.admin.*  # 监控SpringBean
      filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）

      stat-view-servlet: # 配置监控页功能
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false

      web-stat-filter: # 监控web
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      filter:
        stat: # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false
  boot:
    admin:
      client:
        url: http://localhost:8888
  application:
    name: boot-03-web-admin

#mybatis:
#  mapper-locations: classpath:mybatis/mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true

# 配置 actuator 指标监控
management:
  endpoints:
    enabled-by-default: true # 暴露所有监控端点信息
    web:
      exposure:
        include: '*' # 以web方式暴露

  endpoint:
    health:
      show-details: always
info:
  appName: boot-admin
  appVersion: 1.0.0
  mavenProjectName: @project.artifactId@
  mavenProjectVersion: @project.version@
