#spring:
#  web:
#    resources:
#      static-locations: [classpath:/abc/]

#  mvc:
#    static-path-pattern: /res/**

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true

    contentnegotiation:
      favor-parameter: true

#server:
#  servlet:
#    context-path: /pro02